services:
  mysql:
    image: mysql:8.4
    container_name: don5-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: don5
      MYSQL_USER: don5
      MYSQL_PASSWORD: don5
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:7
    container_name: don5-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: don5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: don5-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 512m
    ports:
      - "7474:7474"   # Web UI
      - "7687:7687"   # Bolt
    volumes:
      - neo4j_data:/data
  
  redis:
    image: redis:7
    container_name: don5-redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: don5-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  mysql_data:
  mongo_data:
  neo4j_data:
  redis_data:
  elasticsearch_data:
