services:
  mysql:
    image: mysql:8.0
    container_name: booksta-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booksta
      MYSQL_USER: prj2
      MYSQL_PASSWORD: prj2
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - backend

  spring-app:
    build: ./backend
    container_name: booksta-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booksta
      SPRING_DATASOURCE_USERNAME: prj2
      SPRING_DATASOURCE_PASSWORD: prj2
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

  react-app:
    build: ./frontend
    container_name: booksta-frontend
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - spring-app
    networks:
      - frontend  

volumes:
  mysql_data:

networks:
  frontend:
  backend: